### ISSUE TITLE
[colormap; improvement] reduce number of colormaps  

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#111]
suggestion from @arusstaylor , some colormaps are not that useful for science and we may want to reduce it for v1.1+.

**Comment by veggiesaurus** [comment]
I think we need feedback from users on _which_ color maps to include.  I agree that many are not useful.

My suggestions would be: afmhot, coolwarm, **cubehelix**, **gray**, hsv, **inferno**, jet, **magma**, **plasma**, rainbow, **viridis**.  Bold ones as essential, due to perceptual uniformity, others because they're commonly used in other software packages.

**Comment by arusstaylor** [comment]
This list looks good for an initial set for v 1.1.  There may be others that come as user request later down the road.
