### ISSUE TITLE
use same color as contours for the beam element by default

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1118]
As an enhancement, it would be good to apply the same color as contours to the beam element by default, so that it is easy to tell which beam element belongs to which contour layer. Currently this can be done manually with the image view settings.

**Comment by veggiesaurus** [comment]
two questions:
- What do we do when a colourmap is used? A few options I can think of, in increasing order of difficulty, but also in utility (I think)
    - Revert to white
    - Use some average or midpoint value from the colourmap as the colour
    - Display the colourmap itself on the beam ellipse outline (perhaps from bottom to top)
- Is this link unidirectional or bi-directional? What happens if I manually change the beam colour? What happens if I manually change the contour colour?

**Comment by kswang1029** [comment]
Indeed, this needs a bit more thoughts. 

For 1, I guess reverting to a color is probably good.
For 2, I imagine it is unidirectional. Changing contour color changes the beam color. If beam color changes, the contour color remains the same.

**Comment by kswang1029** [comment]
Will reopen this if we receive requests from users. For now we keep this as simple.
