### ISSUE TITLE
Opening files with special characters in the name from command line

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#1166]
Minor issue raised by beta tester: CARTA can't handle opening images from the command line when they contain a "+" character. I can confirm that the issue is related to the parsing of URL query parameters on the frontend. URLs treat the `+` character as a space and `&` as a separator between query parameters, so we have to encode any special characters in the file or folder names using [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) when generating the URL to load.

**Comment by ajm-ska** [comment]
@veggiesaurus This was indeed easy to fix for the Electron Desktop version using `encodeURIComponent`.
I basically changed `${arg1}` to `${encodeURIComponent(arg1)}`.
It also seems to work if there are special characters in a directory name too.

It might be a little bit hard to test because the [main.js file resides in the carta-package repository.](https://github.com/CARTAvis/carta-package/commit/063367b764a792585343c97b102ba719328078ac#diff-7a9076d6d94e62c13d641aa71f19ae8e)

(I also realised that the v1.4 beta versions don't have the filepath fix that we made a few months ago... The one where the direct URL opening doesn't work if the filepath is shallower than the carta_backend executable. That fix is also included now and will be in the v1.4 release version).

@kswang1029  I think the easiest way to test this would probably to directly replace the existing main.js in the MacOS v1.4-beta.1b version and change the port number on line 9. i.e.
```
cd /Applications/CARTA-v1.4-beta.1b.app/Contents/Resources/app/
mv main.js main.js-old
wget https://raw.githubusercontent.com/CARTAvis/carta-package/master/main.js
sed -i "" "s/54143/53140/g" main.js
```

**Comment by kswang1029** [comment]
@ajm-asiaa yes it works. 

I found another issue with fits images if they have multiple hdu. With the attached image, using command line to load an image does not work.
[spire500_ext.fits.zip](https://github.com/CARTAvis/carta-frontend/files/5140224/spire500_ext.fits.zip)

**Comment by ajm-ska** [comment]
@kswang1029 The main.js file checks for valid files like this:

```
       if (fs.statSync(arg1).isFile() === true) {
//         console.log('DEBUG: File detected');
         //double check that it is a valid filetype for CARTA
          if ( arg1.includes('.fits') || arg1.includes('.hdf5') )  {
            var filemode = 1
//            console.log('DEBUG: File type should be OK', arg1);
            if (items.remote === true) {
              console.log('Error: Can not open an image directly if you are also requesting "--remote" mode')
              process.exit()
            }
          } else {
            console.log('Error: Possibly an unsupported file type');
            process.exit()
         }
       }
```
The characters of`.fits` are still part of `spire500_ext.fits.zip` so it doesn't report that it is an unsupported file type.

When using the CARTA filebrowser, `spire500_ext.fits.zip` does not seem to be visible.

Do you expect that `spire500_ext.fits.zip` should be able to be opened by CARTA, or be caught as an unsupported file type?

**Comment by kswang1029** [comment]
Oh sorry you need to unzip it. It is just GitHub not allowing me to attach a fits file directly.

**Comment by ajm-ska** [comment]
I'm sorry! I should have realised that!

I see what you mean now. When we try to open the unzipped version of that file with direct URL opening, the frontend reports:
![Screenshot 2020-08-28 at 14 49 18](https://user-images.githubusercontent.com/20802551/91530504-c83ded80-e93d-11ea-8697-edabf5cc6975.png)

But in the CARTA filebrowser, it is separated into different files:
![Screenshot 2020-08-28 at 14 49 44](https://user-images.githubusercontent.com/20802551/91530511-cd9b3800-e93d-11ea-9128-f4bbcb02811c.png)

I have no idea how to deal with such a file via direct URL opening using only the main.js file.
@veggiesaurus Do you have any ideas?

**Comment by kswang1029** [comment]
we can always add hdu=0 in the url, maybe? It won't work if the 0 is not an image but mostly it should be.

**Comment by kswang1029** [comment]
it might be possible that hdu=0 is not an image for this file.....

**Comment by kswang1029** [comment]
ok the first hdu is not an image.... so this is an exceptional case. (sorry @ajm-asiaa) We can deal this with in other issues. 

<img width="581" alt="Screen Shot 2020-08-28 at 3 07 46 PM" src="https://user-images.githubusercontent.com/20819712/91532018-456a6200-e940-11ea-91cc-b0d45970c6ef.png">

**Comment by ajm-ska** [comment]
OK. I was just wondering how to add hdu=0 to the URL to get it to work. 

Anyway, you did raise a weakness with: `if ( arg1.includes('.fits') || arg1.includes('.hdf5') )` 
It wouldn't catch if someone tried to open a .zip file, for example (like me 1 hour ago!).

I should change it to `if ( arg1.endsWith('.fits') || arg1.endsWith('.hdf5') )` in order to be more precise.

**Comment by ajm-ska** [comment]
I guess this can be closed now. The initial issue of being unable to open files with special characters from the command line has been fixed.
