### ISSUE TITLE
line query: improve table parser for recombination lines

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1199]
As an example at 1300.7 MHz, we see
![Screen Shot 2020-09-09 at 10 20 14 AM](https://user-images.githubusercontent.com/20819712/92546829-14662780-f286-11ea-9369-f7a6882e4ae9.png)

Splatalgoue gives us
![Screen Shot 2020-09-09 at 10 22 44 AM](https://user-images.githubusercontent.com/20819712/92546996-79218200-f286-11ea-9966-87dd39b2fc75.png)
The resolved and unresolved QN are identical (with parentheses). 

The tsv file looks like
```
Species	Chemical Name	Freq-MHz(rest frame,redshifted)	Freq Err(rest frame,redshifted)	Meas Freq-MHz(rest frame,redshifted)	Meas Freq Err(rest frame,redshifted)	Resolved QNs	Unresolved Quantum Numbers	CDMS/JPL Intensity	S<sub>ij</sub>&#956;<sup>2</sup> (D<sup>2</sup>)	S<sub>ij</sub>	Log<sub>10</sub> (A<sub>ij</sub>)	Lovas/AST Intensity	E_L (cm^-1)	E_L (K)	E_U (cm^-1)	E_U (K)	Upper State Degeneracy	Linelist
17OD	Hydroxyl radical	1300.61380	0.0061			N=2-2,J+1/2=5/2-5/2,p=1--1,F1=2-3,F=1-2	2 1 40 3 2 1 2 -1 40 3 3 2	-8.18440	0.92891	0.00000	-11.10077		46.12200	66.35970	46.16538	66.42212	3.00000	JPL
H&epsilon;	Hydrogen Recombination Line	1300.70000	0			H(291)&epsilon;		H	(	291	)	&epsilon;		0.00000	0.00000	0.00000	0.00000		0.00000	0.00000	0.00000	0.00000	0.00000	Recomb

```

I checked the signatures of the recombination line entries and they look the same. Probably we need to make a custom parser for recombination lines.

**Comment by duidae** [comment]
checked 1300 ~ 1302 MHz:

https://splatalogue.online/c_export.php?&sid%5B%5D=&data_version=v3.0&lill=on&displayJPL=displayJPL&displayCDMS=displayCDMS&displayLovas=displayLovas&displaySLAIM=displaySLAIM&displayToyaMA=displayToyaMA&displayOSU=displayOSU&displayRecomb=displayRecomb&displayLisa=displayLisa&displayRFI=displayRFI&ls1=ls1&ls2=ls2&ls3=ls3&ls4=ls4&ls5=ls5&el1=el1&el2=el2&el3=el3&el4=el4&show_unres_qn=show_unres_qn&submit=Export&export_type=current&export_delimiter=tab&offset=0&limit=100000&range=on&frequency_units=MHz&from=1300&to=1302

the exported tsv is messed up in the beginning & the issue should be that they are using tab in resolved/unresolved QN field instead of space, can also report to Tony for fix.

**Comment by kswang1029** [comment]
Fixed in the splatalogue db.
