### ISSUE TITLE
Export image: long names not fully visible in the Save As field

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-frontend#130]
When we have a long image name, it can not be completely seen in the "Save As:" field. 
In such cases I would expect the text to scroll along with the cursor position, but that does not happen here.
If it is tricky to do, an easy solution might be to make the entire box a lot wider by default?

<img width="408" alt="screenshot 2018-12-21 at 09 56 40" src="https://user-images.githubusercontent.com/20802551/50320403-21b60e00-0507-11e9-9a27-9cacb6e0cacd.png">

**Comment by ajm-asiaa** [comment]
I see on Linux (ubuntu version), it gives a much bigger dialog box. 

<img width="1285" alt="screenshot 2018-12-21 at 12 25 52" src="https://user-images.githubusercontent.com/20802551/50324711-972bd980-051b-11e9-9937-4283a495f6dd.png">

But there could be two small bugs here too:

1. It makes a directory called "squashfs-root" by default. That is a side-effect of using AppImage. When we run an AppImage, I believe it extracts the package into squashfs-root before running it.  

2. We save the image and the dialog box disappears as normal, but if we try to save another image, CARTA seems to hang. But that is because the dialog box has opened behind the Electron window and we do not see it there.

**Comment by confluence** [comment]
I deliberately made the default file names descriptive so that the user would easily be able to recognise which exported files are associated with which original file, but more importantly to avoid collisions. I believe that most browsers will prompt the user before overwriting a downloaded file with the same name, but it's easy to make a mistake and confirm the overwrite. It would also add a tedious manual step for the user if they had to type a unique name for every export to disambiguate them.

If the browser is configured to save downloads without prompting for a name (this may be the default in Chrome, but I'm not sure), this issue is bypassed completely.

We will eventually need to add more complexity to the export to allow the user to select the image format (assuming we still want to offer JPG as an option), in which case we'll probably need to create our own dialog where these options can be selected. We can make that dialog wide enough to display the full default name. My vote would be to defer this issue until then, and not to shorten the default name now. Or at least to keep the timestamp and exported data type, even if the name of the image is removed.

I'm interested in finding out the typical use cases for exporting data. Is it something that a user is likely to do very occasionally, or are users likely to create many exported files for every image, which they need to be able to organise and distinguish efficiently? 

It may be a good idea to let the user save a custom export name format with placeholders that we fill in (functionality analogous to e.g. the way applications for renaming and tagging music files let you set a name format). This could even allow the user to store the exports in a custom tree of subdirectories, although from my cursory search I'm not sure if a browser app can get permission to create a new directory on the local filesystem. We could also let the user save a custom short name for each image, which could be used in the export names instead of the original filename (which may be very long).

**Comment by arusstaylor** [comment]
I concur that better to have a descriptive file name as the default for now, so it is easy to identify the content of an image from the name.

The primary use case is to create figures for presentations and publications.   So png, pdf and eps are additional formats that we should support as a priority.  These are common formats for publications.

Russ

**Comment by jott3077** [comment]
Indeed png, pdf, and eps have the highest priority. After that I see potentially jpeg, ps, gif as useful, but less important formats. 

For the file name, I propose the following: 
use the name of the file itself, add the extension of the exported format. 
If a file with this name already exists, then add a "(1)" "(2)" or similar incremental suffix. It would be great if a message could appear somewhere to mention that the file name was incremented. 
We can also add an 'overwrite' checkbox (default unchecked), that will replace a file if the name already exists.

**Comment by Kechil** [comment]
THis is a browser issue and can't be fixed.
