### ISSUE TITLE
enhancement of spectral matching reference selections

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1302]
ref: https://github.com/CARTAvis/carta/issues/56

in addition to improving the user manual about the default spectral reference (radio velocity), we could consider to add possible options to the context menu (via right-click) of the "matching" column of the image list widget OR we add options in the "settings" dialog (not exist yet) of the image list widget. The could help a bit the UX I guess. @jehibbard @veggiesaurus  thoughts?

**Comment by jehibbard** [comment]
I think using the image list widget probably makes the most sense, since that is where spectral matching is enabled/disabled. But another option could be in the z-line profile widget (or to at least to display what restfreq/redshift is assumed for displaying the red vertical line when the cube is registered to something else)

**Comment by kswang1029** [comment]
@jehibbard lets have the feature of the on-the-fly reference frequency conversion in the spectral profiler as a separate issue. Please help to file a new one in the frontend repo.

**Comment by kswang1029** [comment]
@jehibbard in fact i think the on-the-fly frequency conversion should also happen when matching cubes, not just in the spectral profiler.
