### ISSUE TITLE
Spatial and spectral profile panels; could they be unified?

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-frontend#132]
I am wondering about the difference between the Spatial and Spectral profilers. 
Both 'panels' appear identical and have the same options.
The Spatial profiler 'Coordinate' can be changed to X or Y in a drop down menu. 
But the same setting in the Spectral profiler can only select Z in a similar drop down menu. 

I understand that they work differently (X and Y profiles are calculated on the frontend, and the Z profile is calculated from the backend), but would it be possible to combine them so that there is only a single Profile panel that the user could select X, Y or Z from the panel's Coordinate menu?

Also, in the current widget bar there is a Spatial profile and a Spectral profile button. The Spectral profile button shows a Z, and the Spatial profile button show an XY. But when you click it, it only opens an X profiler. You need to change it to an Y in it's Coordinate setting menu. 
Would it be a good idea to have two Spatial profile buttons there? One for X and one for Y?

Finally, I know the wave-like symbol on the buttons indicate "profiler", but would it be better to have different symbols between spatial and spectral profiler buttons to further differentiate them?

<img width="172" alt="screenshot 2018-12-21 at 10 15 20" src="https://user-images.githubusercontent.com/20802551/50372427-2a8f0880-0609-11e9-838e-e33dcdf87941.png">

**Comment by veggiesaurus** [comment]
In the short term, I'd like to leave the icons as they are, because we struggled to find appropriate icons from the blueprint library (https://blueprintjs.com/docs/#icons) that didn't clash with other icons used elsewhere. If anyone has any suggestions, let me know, but @kswang1029 and I have looked, and thought the pulse with the superscript was the best solution

Also in the short term, I like the idea of having two spatial profile buttons, one for X and one for Y. See below for an example of how that would look. 

![image](https://user-images.githubusercontent.com/592504/50372820-30bbbf80-05de-11e9-93de-2619b2fcf6ed.png)

Long terms, I agree that we should look at unifying the spectral and spatial profilers. Two difficulties that I forsee with that:

1. The data flow for the two is quite different, and will likely continue to be quite different for all files except HDF5 files, due to how long spectral profiles take to compute. In future, we should look at how to optimise these data flows and make a profiler widget that is flexible enough to deal with different data flows. 

2. The choice of regions for spectral and spatial profiles is different. Spatial profiles can be associated with a point region or (eventually) a line/curve region. Spectral profiles can be associated with a point region, closed region (rectangle, ellipse, polygon). So switching from one coordinate to another would also require the user to change which region the profiler is associated with (unless it's a point region). May lead to some confusion there. 

@arusstaylor has also requested this feature. Perhaps something for the f2f discussion?

**Comment by arusstaylor** [comment]
On further thought, z-profiles have a different purpose and use-case from a spatial profile.  I would favour maintaining separate profiles tools for the spatial and spectral case.  For one thing it is very convenient for the user to be able to just select a tool button to show the z-profile.. Otherwise would need to bring up a profile tool and then set the profile to z.

**Comment by Kechil** [comment]
Cannot be unified.
