### ISSUE TITLE
adding colorbar setting options to preferences dialog

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1372]
Once https://github.com/CARTAvis/carta-frontend/pull/1366 is merged, in the preference dialog, we need a "Colorbar configuration" tab and provide options so that users can configure their own defaults of the colorbar styling.

**Comment by veggiesaurus** [comment]
can we make these settings implicitly set as well?

**Comment by YuHsuan-Hwang** [comment]
I think it may not be a good idea to make the settings implicit because we are only adding some of the settings to the preference dialog. If we make them implicit, some settings in the image view settings will remain when reopening CARTA but some will not. Users may not easily predict this behavior and may take time to be used to it.
I think it’s hard to decide if the user need a setting remain or not because it’s different from person to person and from case to case. It is more simple and clear to me to just use the preference dialog when necessary.
