### ISSUE TITLE
Blueprintjs v4 upgrade

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1395]
https://github.com/palantir/blueprint/wiki/Blueprint-4.0

aiming carta >= v3.0

**Comment by veggiesaurus** [comment]
that was fast for a Saturday evening, @kswang1029 😆

**Comment by kswang1029** [comment]
need to monitor the v4  release schedule then we can get this issue scheduled in our development cycle.

**Comment by kswang1029** [comment]
@veggiesaurus @YuHsuan-Hwang just found that v4 has been released (finally).

**Comment by veggiesaurus** [comment]
Blueprint 5 is now out and stable. It's a minor update on BP4. Having recently gone through a similar upgrade, some things I've learnt:

We can make our lives much easier by doing prep work _before_ the actual upgrade:
  - use proper class names in typescript from the `Classes` import
  - use the `ns` variable in SCSS instead of `bp3` or `bp4` prefixes
  - Start moving away from deprecated components and use their replacement components instead. Some are for example popover, tooltip, menuitem and overlay 

Once we've made these changes we can proceed with the upgrade.
