### ISSUE TITLE
independent clip range per Stokes

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#148]
need to able to set the clip range independently for each Stokes.

**Comment by veggiesaurus** [comment]
In terms of implementation, this requires that each Stokes sub-cube has its own selected percentile  (either a valid percentile or "custom"), and its own clip values if the selected percentile is "custom". 

The idea here being that the user can change the custom clip levels to an appropriate range for each Stokes cube independently, rather than being forced to use (a) the same percentile for each cube or (b) the same absolute clip levels for each cube. 

This is a relatively minor change, but will require some testing. @kswang1029 not sure which release to aim for. 1.2?

**Comment by arusstaylor** [comment]
Is it at all possible to get this into 1.1?  There will be lots of Stokes I viewing from April to June on the MeerKAT side.

**Comment by veggiesaurus** [comment]
implemented in #202
