### ISSUE TITLE
inconsistent values in cursor info bar and spatial profiler 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#154]
When the image is not downsampled, the displayed value in the cursor info bar should be consistent with the data value in the spatial profiler, at least to the displayed digits. Following is an example.
<img width="1436" alt="screen shot 2019-03-04 at 09 39 46" src="https://user-images.githubusercontent.com/20819712/53705809-fd10d780-3e61-11e9-81f4-9aa9a9e6ae88.png">

Is this something to do with the compression quality?

**Comment by veggiesaurus** [comment]
yes, this is related to compression quality. My initial suggestion is that we use the spatial profile values in the cursor par, to fix this, #116 and #150. However, the _right_ way to do it would be to enable this feature even if the spatial profiles are not required from the backend. In which case, there may need to be an ICD change, @pford and I can discuss.

**Comment by veggiesaurus** [comment]
@kswang1029 we now use full-resolution and uncompressed spatial profiles to get the cursor value, so this should be sorted out. However, because the decimated profiles combine multiple pixels into one, by selecting the min and max in a group, the position of the image view cursor can be subtly different from the position of the profile cursor. 

For example, if your image view cursor is at `{12, 12}`, and your spatial profile is decimated by a factor of 8, then the cursor on the spatial profile will be "somewhere between 8 and 15", since all those points correspond to the same pixel as 12. So the value displayed on the spatial profiler will be the position and value of the max value between 8 and 15. Still inconsistent with the image view cursor, but now not fundamentally inaccurate.
