### ISSUE TITLE
Additional tutorial entries for code snippets

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#1556]
Additional tutorial entries are needed for the following:

- [ ] Changing FoV, channels and Stokes of images
- [ ] Adjusting render config
- [ ] Creating regions

@kswang1029 may have more suggestions on what to add after testing out the code snippets feature in more detail

**Comment by kswang1029** [comment]
suggestions for improvements:

1. when we click the "New" button in the snippets dialog, we should ask users to save or discard the snippets in the current editor.
2. the overwrite confirmation popup shows _behind_ the save popup.

https://user-images.githubusercontent.com/20819712/125237324-153d6f00-e318-11eb-9e9b-0a8961001635.mov

3. (no standard use case🙈) if we keep the enter key pressed to create new lines, at some point (~1000 lines with my laptop) we will see it slows down (ie not seeing each new line being created, instead it jumps every few lines)


questions:
1. should we consider to use a widget instead of a dialog? with a widget it might be easier to write a script by referencing the GUI _interactively_. With a dialog, the rest of the GUI is blocked (for example, we cannot see what categories that have been created from the snippets menu. BUT if we do so, we can have multiple snippets widgets activated at the same time.
2. what's the purpose of having "tag" and where to see it other than the save popup?

**Comment by veggiesaurus** [comment]
moving this and #1482 to the final 3.0 beta milestone, as it is low-risk

**Comment by keflavich** [comment]
Bump - are there any existing tools for loading regions?

**Comment by veggiesaurus** [comment]
> Bump - are there any existing tools for loading regions?

@keflavich you can load regions into the current active image using 
```javascript
await app.importRegion(directory, filename, regionType);
```
where `regionType` is the region type enum value. `CRTF = 1` and `DS9 = 2`.

**Comment by keflavich** [comment]
perfect, thank you!

Related: is there a `delete` for regions?  If I open a region file that has 100x, say, is there a scripty way to delete them?

**Comment by veggiesaurus** [comment]
> perfect, thank you!
> 
> Related: is there a `delete` for regions? If I open a region file that has 100x, say, is there a scripty way to delete them?

This might be a bit slow for 100 regions (it will do a filter for _each_ deletion, so it probably _O(N²)_. I'd like to add a `.clearRegions` function too, because this is probably quite a common use case):

```javascript
for (const region of app.activeFrame.regionSet.regions) {
    app.activeFrame.regionSet.deleteRegion(region);
}
```

**Comment by keflavich** [comment]
yes, I think there are a lot of different region-related functions that could use additional support, and I'd be happy to expand on them somewhere if you'd like - but I suspect you guys have a checklist somewhere?

Anyway, thanks, this will work at least to clear out regions without clicking a ton.

**Comment by veggiesaurus** [comment]
> yes, I think there are a lot of different region-related functions that could use additional support, and I'd be happy to expand on them somewhere if you'd like - but I suspect you guys have a checklist somewhere?
> 
> Anyway, thanks, this will work at least to clear out regions without clicking a ton.

Feel free to send me a list of requested functions/tutorials/etc. Quite a few might already be easily done.
