### ISSUE TITLE
revisiting SET_CURSOR criteria 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1587]
The SET_CURSOR message is only triggered when the cursor position as "whole pixel" is updated. So if there are matched  images with very different pixel sizes, we will see relevant info such as cursor value (cf @YuHsuan-Hwang 's work on the cursor info widget), cursor spatial profile or cursor spectral profile not being updated.  

Taken the following figure as an example, if we move the cursor inside the pixel highlighted with thick red line, on the matched image (with black color) there are multiple smaller pixels. So in principle if we move the cursor around inside the red pixel, we should still be able to see data update of the cursor hits a new black pixel.

![Screen Shot 2021-07-27 at 11 54 17 AM](https://user-images.githubusercontent.com/20819712/127092958-47c1545f-1c18-4c7c-906e-2281fbde62a5.png)

A possible solution would be we refine the criteria of SET_CURSOR to support fractional pixel down to 1/1000 (not perfect as the same issue still happens at a smaller scale). This would extend the use cases significantly I suppose.

**Comment by YuHsuan-Hwang** [comment]
Had a deeper look at this issue:
1. matched images pixel values are not updated
We check the image position with very high precision, but then we obtain the positions of the matched images using the _rounded_ position of the reference image. This can be simply solved by rounding the position after obtaining the positions
2. hovering event only responsive to the active image
When hovering over a non-active image in multi-panel mode, the cursor value is never updated. Need to response to all displayed images instead of the active image. Also need to adjust the display criterion of the cursor info widget
![image](https://user-images.githubusercontent.com/43841102/131079297-da0c0464-4071-45d1-b86e-83a3fb3d26ac.png)
