### ISSUE TITLE
regression: cannot load large catalog 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1652]
In my test env, I tried to load a catalog with 100M sources.
with
- latest dev : the frontend soft crashed after streaming ~5.5M sources
- v3b1 Mac electron build: frontend hard crash at ~5.5M
- v2.0: it seems to load fine at the time of filing this issue (~24M) and keep streaming. UPDATE: I killed the process at ~33M as my OS is swapping a lot...

with dev I see
![Screen Shot 2021-09-10 at 1 56 51 PM](https://user-images.githubusercontent.com/20819712/132807785-82a5b737-13d0-4d45-ba23-84630b8516f5.png)

**Comment by veggiesaurus** [comment]
So does a 10M catalogue load ok in 2.0?

**Comment by kswang1029** [comment]
> So does a 10M catalogue load ok in 2.0?

Yes, 10M catalog can be loaded successfully. v3b1 and dev can load it successfully too.

**Comment by kswang1029** [comment]
@kswang1029 to double check if it still exists in dev and v4-beta

**Comment by kswang1029** [comment]
@veggiesaurus I tried with dev and v4-beta, the issue persists. When loading a 100M-source catalog, at around 6M sources rendered, the frontend shows errors as
<img width="540" alt="Screenshot 2023-06-01 at 12 02 58" src="https://github.com/CARTAvis/carta-frontend/assets/20819712/7f645602-b41f-4b45-bad6-a0a026d320ba">

However, if we load a catalog with just 10M sources, everything is fine.

**Comment by YuHsuan-Hwang** [comment]
When loading 100M sources, we initialize an array with size 100M in the very beginning. Looks like this is using up all the memory, and we get the [`invalid array length` error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length).

We could limit the initial size of the array to 20-30M and expand it after more sources are loaded, but it may not be worth doing because we still may not be able to load all the sources, and the number highly depends on browsers.

I would suggest we close this issue and file new issue in the future if there are user requests.

(I’m not sure if this is a regression. Related codebase is not changed since v2.0, and I could not load 100M sources with v2.0 electron app.)

([ref](https://stackoverflow.com/questions/70198991/javascript-pre-allocated-array-uncaught-rangeerror-invalid-array-length))

**Comment by kswang1029** [comment]
> When loading 100M sources, we initialize an array with size 100M in the very beginning. Looks like this is using up all the memory, and we get the [`invalid array length` error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length).
> 
> We could limit the initial size of the array to 20-30M and expand it after more sources are loaded, but it may not be worth doing because we still may not be able to load all the sources, and the number highly depends on browsers.
> 
> I would suggest we close this issue and file new issue in the future if there are user requests.
> 
> (I’m not sure if this is a regression. Related codebase is not changed since v2.0, and I could not load 100M sources with v2.0 electron app.)
> 
> ([ref](https://stackoverflow.com/questions/70198991/javascript-pre-allocated-array-uncaught-rangeerror-invalid-array-length))

I suggest we still address the 5.5M limitation as reported in the issue. 100M support can be in the far future.

**Comment by kswang1029** [comment]
Tested with v4-stable and 10M catalog is supported (using 11GB RAM in my test case). Close for now.
