### ISSUE TITLE
Line gap in the spatially matched selected region

### ISSUE THREAD

**Issue by acdo2002** [CARTAvis/carta-frontend#1740]
Method to produce this issue:
(1) Load two all sky images (e.g. I load "Halpha_map.fits" as the first image and I load "ovro_mollweide_lwa_sky_map_36.528MHz.fits" as the second image)

(2) Set a long line region in the first image
(3) Select the second image and click the WCS spatially matching.

The long line region in the second image will show a gap in the line.
![line-region-gap](https://user-images.githubusercontent.com/34430648/144566577-424c4a33-1c9a-4b15-b02d-79b2dc1a6944.png)

This issue has been already existed in the `CARTA-v3.0.0-beta.CUC2021-ubuntu.AppImage`

**Comment by YuHsuan-Hwang** [comment]
The issue is caused by point sampling for projecting unclosed regions, i.e. polygon (under creation), polyline and line regions, in `getApproximatePolygonPoints` in `utilities/wcs.ts`.  The effect can be clearly observed if we set the sampling number `RegionStore.TARGET_VERTEX_COUNT` from 200 to 10:

<img src="https://user-images.githubusercontent.com/43841102/173795849-e2a6c759-18ff-45a6-bc3b-f9933cc4c631.png" width="300" /> <img src="https://user-images.githubusercontent.com/43841102/173795921-93dab701-ab1f-415a-ad38-39f316557445.png" width="300" />
<img width="300" alt="image" src="https://user-images.githubusercontent.com/43841102/174237908-9cdaeb99-04db-4783-b68d-24c119daf44b.png">
