### ISSUE TITLE
Root menu warning

### ISSUE THREAD

**Issue by YuHsuan-Hwang** [CARTAvis/carta-frontend#2116]
**Describe the bug**
Warning from the root menu component. A regression after v3 release.

**To Reproduce**
Launch Carta and check the console

**Expected behavior**
No warnings

**Screenshots or videos**
<img width="770" alt="image" src="https://user-images.githubusercontent.com/43841102/224623165-c1c34288-ce07-4fb5-82d0-ab01073cb7b4.png">

**Platform info (please complete the following information):**
 - OS [e.g. macOS Monterey]: macOS Big Sur
 - Browser [e.g. chrome, safari, electron app]: chrome
 - Browser version [e.g. 22]: 108
 - Backend branch [e.g. dev, v3b2 release]: dev, not in v3 release
 - Frontend branch [e.g. dev, v3b2 release]: dev

**Additional context**

**Comment by kswang1029** [comment]
@YuHsuan-Hwang I don't see such error in my dev builds. This is what I saw
![Screen Shot 2023-03-13 at 17 06 39](https://user-images.githubusercontent.com/20819712/224655823-50893768-edc9-4598-833e-d112ca1ec671.png)

e2e tests are all passing though. This is with Chrome 110 on macOS Monterey.

**Comment by acdo2002** [comment]
short confirmation because I am designing and implementing the ICD tests on Mark's swapped axes branch.
The same warning message on my MacOS 11 with Google chrome
<img width="592" alt="Screen Shot 2023-03-13 at 5 43 42 PM" src="https://user-images.githubusercontent.com/34430648/224665488-d94a7a8f-aae9-4c43-9b7d-7d7657097cf3.png">

OS [e.g. macOS Monterey]: macOS Big Sur 11.6
Browser [e.g. chrome, safari, electron app]: chrome
Browser version [e.g. 22]: 109
