### ISSUE TITLE
[region spectral profiler] region dropdown of spectral profiler when multiple images exist

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#213]
The region dropdown menu resets to "cursor" when changing frames via animator and it is empty.

To reproduce the issue:
1) open two images (A and B) with the append mode
2) define a region for each image (r1 in A, r2 in B)
3) in spectral profiler widget, set region to r1 (animator now with the frame A)
4) now switch to frame B
5) repeat 3) but select region r2
6) now switch back to frame A
7) expect to see a profile of r1 but it is cursor and it is empty

demo below
![specpro](https://user-images.githubusercontent.com/20819712/55204986-faf52b00-520b-11e9-9ca1-e736b6c4c0a4.gif)

**Comment by veggiesaurus** [comment]
I remember we decided that each frame should have its own selected region, right? So when adding a new frame, it defaults to Cursor (or in the case of stats or histogram, Image), but switching between different frames would also switch which region is selected, rather than jumping back to Cursor

This may be a simple fix if we just switch from a single `regionId: number` to a map between `frameId` and `regionId`. Related to this is how profile's coordinate choices behave when a frame is closed.

**Comment by kswang1029** [comment]
Yes, each frame should have its own set of regions. And for each frame it is okay to have "cursor" region as default. However, once it is changed to a specific region in each frame, each frame should remember which one is selected when changing frame with the animator.

**Comment by veggiesaurus** [comment]
@kswang1029 please test with frontend build `2105ab3` (branch `angus/fix_widget_region_selection`)

**Comment by kswang1029** [comment]
Great! Works well. 👍

**Comment by arusstaylor** [comment]
Might also be good to have regions that apply globally to all frames, for the use case where you wish to compare statistics for the same region in multiple images.

Russ

**Comment by veggiesaurus** [comment]
> Might also be good to have regions that apply globally to all frames, for the use case where you wish to compare statistics for the same region in multiple images. Russ

@arusstaylor this will be handled through WCS groups in 1.2. A region will be associated with a single WCS group, and can then be used to compare between different files in the same WCS group.
