### ISSUE TITLE
[render config] histogram ranges for different channel/stokes

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#221]
with the default 99.9% clip, the x-range of the plot changes with different Stokes (which is good). However, if the x-range of a given Stokes is changed by users via mouse interactions, then the x-range is fixed to all Stokes. I encountered a case that I zoom in the Stokes=0, then switch to Stokes=1, and the plot is empty. Since it is empty there is no way to use mouse db-click to reset the range. I will need to use the reset range button in the settings menu to cure this.

Same happens when changing channels. Changing images seem okay.

**Comment by veggiesaurus** [comment]
two thoughts: 
1) You should still be able to double click to reset the range. @duidae can look into that, since he fixed that for the spectral profilers
2) For other widgets, it might make more sense to preserve the chosen range, but for the render config widget, I think it makes sense to reset whenever the data is changed, what do you think?

**Comment by kswang1029** [comment]
right, for spatial/spectral profiles, preserving x-range is good, as users can keep focusing on features.

**Comment by duidae** [comment]
double click works & reset render config is done in PR #222
