### ISSUE TITLE
Scripting interface

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#226]
to provide the interface in python3 to control CARTA.

**Comment by dmehring** [comment]
I've written methods such as close_file(), open_file(), register_viewer(), set_image_view(), set_user_preferences() and have tested their sanity using a mock server. I'm using our scripting interface to plotms as a guide as to how to set up the file structure. This structure relies on relative directory python imports which seems to clash with the carta-protobuf layout, since when translated into python, the imports are not relative. So, at least for now, I've had to create a monolithic .proto file containing all the definitions.

**Comment by dmehring** [comment]
Still awaiting requirements for minimal feature set needed in next release. Such requirements include method names (probably no more than two or three for the proof of concept release), associated parameter names, return types/values, and basic behavior desired.

**Comment by veggiesaurus** [comment]
@kswang1029 do we have a list of non-controversial functions needed? Just something for @dmehring to get started on.

I'd think that at the very least a starting point would be:
- `openFile(filename: string) => int` open a file by specifying a path. This should return the open file's `fileId`.
- `closeFile(fileId: int) => bool` close a file by specifying `fileId`. Returns `true` if an image with the supplied `fileId` exists.
- `setImageChannels(fileId: int, channel: int, stokes: int) => bool` set a given image's channels and Stokes for a given `fileId`. Returns `true` if the `fileId` exists, and the supplied `channel` and `stokes` values are valid.
- `setImageView(fileId: int, xMin: float, xMax: float, yMin: float, yMax: float) => bool` sets the image view for a given `fileId`. This may result in the frontend asynchronously requesting tiles from the backend. Returns `true` if an image with the given `fileId` exists, and the supplied image bounds are valid (`xMin < xMax` and `yMin < yMax`).
- `setActiveImage(fileId: int) => bool` set active image by supplying a `fileId`. Returns `true` if an image with the given `fileId` exists.
- `setRenderClipBounds(fileId: int, min: float, max: float) => bool` sets the clip bounds for the image specified by `fileId`. Returns `true` if an image with the given `fileId` exists.
- `setRenderColormap(fileId: int, colormap: string) => bool` sets the colormap for the image specified by `fileId`. Returns `true` if an image with the given `fileId` exists _and_ the colormap specified by `colormap` exists.
- `getRenderedImage() => ???` Renders an image (may require the frontend blocking until the backend has sent through all the required image tiles), and returns it in an appropriate image format (perhaps a base64-encoded PNG dataUrl would be easiest).

Given that CARTA loads default values for colormaps, clip bounds, FoV and channels, the user would only need to call `openFile`, followed by `getRenderedImage` in order to produce a rendered image of a given file.

**Comment by veggiesaurus** [comment]
After a conversation with @kswang1029, we think it would be useful to wrap the above functions in something more object-oriented, so that the two are equivalent:

```
# connect to an existing CARTA session
sessionId = carta.connectToSession(ip, port, sessionId)
if sessionId < 0:
   # handle errors with connection to session
   return

# add a file
fileId = carta.openFile(sessionId, path)
if fileId < 0:
    # handle errors with opening file
    return

if carta.setImageChannels(sessionId, fileId, channel=5, stokes=0):
    carta.setRenderColormap(sessionId, fileId, colormap="plasma")
    imageBlob = carta.getRenderedImage(sessionId, fileId)
    # do something with the image blob (base64 PNG)
```

```
# connect to an existing CARTA session
session = carta.connectToSession(ip, port, sessionId)
if session is None:
   # handle errors with connection to session
   return

# add a file
image = session.openFile(path)
if image is None:
    # handle errors with opening file
    return

if image.setChannels(channel=5, stokes=0):
    image.setRenderColormap(colormap="plasma")
    imageBlob = image.getRenderedImage()
    # do something with the image blob (base64 PNG)
```

**Comment by dmehring** [comment]
Thanks @veggiesaurus 
So, in your previous comment, you’d like the more OO approach of the second group of statements to be used in preference to the first group, is that correct? My module already uses such an OO approach, so if you haven’t already, please take a look at my module and let’s start there so I know what I have to change in the basic design and what I don’t. Again, you should have access to the source code at https://open-bitbucket.nrao.edu/projects/CASA/repos/

A code style comment is that your use of camel case for method and variable names does not adhere to the recommended python convention of using all lower case characters for these names with underscores to represent spaces. Do you object to this python convention which I have used thus far? 

https://www.python.org/dev/peps/pep-0008/

**Comment by veggiesaurus** [comment]
@dmehring yes, I think an OO approach similar to your code should work nicely. 

On the subject of style, you’re quite right. Sorry, I was multitasking and coding in JavaScript, so my code styles got a bit mixed up...

**Comment by dmehring** [comment]
The initial set of requirements I received in September had the notion that one would have to register the associated viewer/front end using the python client before one could proceed with eg, image operations. However, the requirements in this ticket do not seem to have anything similar to that. Does the python client need to explicitly register the viewer, or will that be taken care of by the backend when the python client connects to it to create a Session object?

**Comment by dmehring** [comment]
`session = carta.connectToSession(ip, port, sessionId)`

Should the user be permitted to specify the sessionid? It seems that this is something the client should manage internally, especially if a single client is permitted to open multiple simultaneous sessions (in which case uniqueness of session IDs must be assured), which this model seems to imply.

**Comment by dmehring** [comment]
`image = session.openFile(path)`

The OpenFile rpc requires the hdu. Is that part of the path in this call? If so, how is it specified? Should there be a default value for the hdu so the user doesn't have to specify it and so something sensible will happen if it is not specified?

Also, what if the backend (server) is running on a different machine than the (python) client? Is the file specified understood to be on the client machine? How is then the file transferred for display? Perhaps for the proof of concept version, the server and client must be constrained to run on the same machine so no image transfers between them is necessary?

**Comment by veggiesaurus** [comment]
> The initial set of requirements I received in September had the notion that one would have to register the associated viewer/front end using the python client before one could proceed with eg, image operations. However, the requirements in this ticket do not seem to have anything similar to that. Does the python client need to explicitly register the viewer, or will that be taken care of by the backend when the python client connects to it to create a Session object?

Registering the viewer is done automatically by the frontend. I think you are conflating the two interfaces (frontend/backend vs backend/python).

**Comment by veggiesaurus** [comment]
> `session = carta.connectToSession(ip, port, sessionId)`
> 
> Should the user be permitted to specify the sessionid? It seems that this is something the client should manage internally, especially if a single client is permitted to open multiple simultaneous sessions (in which case uniqueness of session IDs must be assured), which this model seems to imply.

This may be necessary, if a single backend is supporting multiple frontends. Each frontend should have at most one scripting interfaces controlling it. I suggest if a user attempts to connect from python with the same session ID as one which already has a scripting interface attached, the RPC should fail.

**Comment by veggiesaurus** [comment]
> `image = session.openFile(path)`
> 
> The OpenFile rpc requires the hdu. Is that part of the path in this call? If so, how is it specified? Should there be a default value for the hdu so the user doesn't have to specify it and so something sensible will happen if it is not specified?

The default value should be the first HDU. Currently, if the frontend doesn't pass an HDU to the backend, the first HDU is opened. 

> Also, what if the backend (server) is running on a different machine than the (python) client? Is the file specified understood to be on the client machine? How is then the file transferred for display? Perhaps for the proof of concept version, the server and client must be constrained to run on the same machine so no image transfers between them is necessary?

The files are all relative to the _server_.

**Comment by dmehring** [comment]
@pford According to @veggiesaurus 

**The files are all relative to the server.**

This would seem to not support the model in which the user is also interacting with CASA on the client machine from the same python interface. eg, it does not seem to support the usage example

‘’’from carta import backend
from casatools import image as ia
backend.connect(.. .)
ia.open(‘myimage.image’)
ia.function1(outfile='mynewimage.image',...)
ia.function2(outfile='mynewimage.image',...)
ia.function3(outfile='mynewimage.image',...)
‘’’
from

https://docs.google.com/document/d/1B_hiNRXVSGNBO9s8emAu5VHyVYmt6u4s5xNbFIrkEak/edit#heading=h.25cdsfyhqu4p

because the CARTA file location is on the server, but the CASA file location must be on the client (local) machine. 

Do you agree or am I missing something?

**Comment by pford** [comment]
@dmehring CASA and the CARTA backend server read the image data from disk, so they both need to be running where they can access the image filesystem.  The CARTA scripting client and frontend client can be run on the same CASA/CARTA machine or another machine, communicating with the backend locally/remotely through gRPC (scripting client) or uWebSockets (frontend client) sockets.  The backend can connect to one or more frontend clients, e.g. the user connects two browsers to the same server URL.  Each connection increments the session number starting at 0 (first connection is 1).

@veggiesaurus how does the user know their session ID?  If the user starts carta with `carta --remote`, is there a session to connect to?

**Comment by veggiesaurus** [comment]
> @veggiesaurus how does the user know their session ID? If the user starts carta with `carta --remote`, is there a session to connect to?

The session would only be started once they open the frontend. At that point, their terminal would display the session number. I think in general, we should display the session number in the frontend log as well, or in the connection info tooltip over the connection indicator

**Comment by dmehring** [comment]
Re: session ID and python interface. So, it sounds like the user must specify an already existing session ID, which they will know in advance, when connecting from the python client to the backend.

**Comment by veggiesaurus** [comment]
> Re: session ID and python interface. So, it sounds like the user must specify an already existing session ID, which they will know in advance, when connecting from the python client to the backend.

if the session ID is left out in the python interface, do you think the backend should just use the first session (if it exists)

**Comment by confluence** [comment]
Are we not going to allow the option of using a headless browser? That would seem to be the most sensible default option (e.g. if the user doesn't want to steer a display interactively, but just wants to export some images).

Assuming I'm understanding this correctly, I think the wrapper should allow the user to specify an existing session ID *or* to create a headless browser session (the wrapper would extract the session ID from that and manage it internally). These modes should be unambiguous; I don't think we should try to guess the session.

**Comment by kswang1029** [comment]
@dmehring @pford from your point of view, what material should the science team provide to assist development?

**Comment by dmehring** [comment]
> Are we not going to allow the option of using a headless browser? That would seem to be the most sensible default option (e.g. if the user doesn't want to steer a display interactively, but just wants to export some images).
> 
> Assuming I'm understanding this correctly, I think the wrapper should allow the user to specify an existing session ID _or_ to create a headless browser session (the wrapper would extract the session ID from that and manage it internally). These modes should be unambiguous; I don't think we should try to guess the session.

I'm guessing a headless mode would be desirable for our users for some use cases. Because it seems that current (non-headless) session IDs are >0, I could make the default session_id  0 and that would indicate that headless mode should be used. Does that sound reasonable?

**Comment by dmehring** [comment]
> @dmehring @pford from your point of view, what material should the science team provide to assist development?

My initial confusion is what should happen in the case where the user wants to run CASA on one machine but connect to a CARTA backend on another machine if they desired some sort of interaction between CASA and CARTA. The interaction of CASA and CARTA seems to be one of the main use cases Ryan wants addressed. That is, for example

1. Create a new image with CASA
2. Display that new image using CARTA by using the python client to send a request to the backend

This works pretty easily if the backend and CASA are being run on the same machine, but not so much if they are being run on different machines, since the backend wouldn't have access to the newly created image. However, in discussing with Ryan, it seems like the normal mode of operation, at least in the short term, would indeed be to run CASA and the backend on the same machine. I guess that's a good enough assumption, at least for the proof of concept version of the python client.

**Comment by pford** [comment]
It could be a shared filesystem such as lustre.  If my workstation and the carta server have lustre access, I could run CASA on my workstation to create an image ("/lustre/aoc/users/pford/my.image") then use the scripting interface to connect to the carta server and open the image:

import carta
bk = carta.Backend(uri=carta_server_uri, session_id=1, auto_register=True, debug=False) 
bk.open_file(directory='/lustre/aoc/users/pford', filename='my.image', hdu='', file_id=0, render_mode="raster")

**Comment by dmehring** [comment]
> It could be a shared filesystem such as lustre. If my workstation and the carta server have lustre access, I could run CASA on my workstation to create an image ("/lustre/aoc/users/pford/my.image") then use the scripting interface to connect to the carta server and open the image:
> 
> import carta
> bk = carta.Backend(uri=carta_server_uri, session_id=1, auto_register=True, debug=False)
> bk.open_file(directory='/lustre/aoc/users/pford', filename='my.image', hdu='', file_id=0, render_mode="raster")

Right, it could be. My initial confusion arose for the general case where the machines and file systems were different (or file systems the same, but different users running the different processes so the file permissions might cause issues), since, for CASA and CARTA to be able to interact in the same python session in that case, at best one would have to transfer the image somehow. But, it doesn't appear that we are to concern ourselves with that use case for now.

**Comment by dmehring** [comment]
I've just pushed a significant rewrite of the code using the OO  paradigm. I think I'm nearly done. What Ryan seems to want from our side for the upcoming release is for users to be able to locally save plots of images to common formats such as png. I'm guessing this command from @veggiesaurus' previous comment is meant to enable that:
```
imageBlob = image.getRenderedImage()
    # do something with the image blob (base64 PNG
```
Is the idea here that imageBlob will be a string representing the image encoded in base64 that can be then be converted to other formats, such as PNG, for export locally?

**Comment by pford** [comment]
I have updated Juergen's doc listing the NRAO use cases to describe the user interface, combining his use cases with the sample python session in the comments here.  This shows the interface that exists in the current python client (updated with the repo README after Dave's comment about his rewrite), what needs to be done for release 1.3 (IMO), and what will be added later.

@dmehring I added "image.save()" in case the user wants to save the image where the frontend client is running.  Then the frontend can just save the image to disk as usual without the python middleman.

All, please review this doc and make comments and changes.  This should improve coordination on this feature.

https://docs.google.com/document/d/1Rm88mscy6CCWLnNxJe3WaGvDVdW8pqyPm5AvXPosm6Y/edit#

**Comment by dmehring** [comment]
>     image.setRenderColormap(colormap="plasma")

I don't see an existing  protobuf message for this. Is there one? If not, what are the choices of colormaps?
Thanks

**Comment by pford** [comment]
Right, usually this is set in the GUI and the backend doesn't need the colormap.  In carta-frontend/src/stores/RenderConfigStore.ts,
`static readonly COLOR_MAPS_SELECTED = [
        "afmhot", "Blues", "coolwarm", "cubehelix", "gist_heat",
        "gist_stern", "gnuplot", "gnuplot2", "gray", "greens",
        "greys", "hot", "inferno", "jet", "magma",
        "nipy_spectral", "plasma", "rainbow", "RdBu", "RdGy",
        "reds", "seismic", "spectral", "tab10", "viridis"
    ];`

These are are the options shown in CARTA.  Looks like default is 'inferno'.

**Comment by dmehring** [comment]
I've completed the python client work for the 1.3 requirements from https://docs.google.com/document/d/1Rm88mscy6CCWLnNxJe3WaGvDVdW8pqyPm5AvXPosm6Y/edit# . The backend code will obviously need to be updated to support the python client requests. Let me know if you need anything further from me.
Thanks
