### ISSUE TITLE
with electron app, cannot copy statistics values from the GUI

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#241]
with server version, yes, statistics values can be copied and pasted. But with the electron app, we cannot.

**Comment by ajm-asiaa** [comment]
This is due to the fact that menus have been disabled in Electron. We disabled menus so as not to clash with CARTA's built in File View Layout and Help menus, particularly on RedHat7 where the Electron menu would appear directly above the CARTA menu. It would not be so bad on MacOS and Ubuntu as the Electron menu would appear at the top of the screen.

On MacOS there is still a small menu that appears with a quit option:
![Screenshot 2019-04-22 at 15 00 17](https://user-images.githubusercontent.com/20802551/56488490-16084180-6511-11e9-8487-019e7921f183.png)

As a quick experiment, I have added Cut, Copy, and Paste options to this menu
![Screenshot 2019-04-22 at 15 07 22](https://user-images.githubusercontent.com/20802551/56488526-30421f80-6511-11e9-8b1f-76ed680787b8.png)
(I'm not sure where the Start Dictation and Emoji & Symbols is coming from)

Anyway, I can now copy statistic values. 

Maybe we could just have a separate Edit menu beside it instead?

**Comment by kswang1029** [comment]
I see. To be more consistent with a typical mac app, having a separate "Edit" menu is better I would suggest.

**Comment by ajm-asiaa** [comment]
OK. Next, is it worth leaving a standard edit menu (e.g. same as Firefox) with some options that can not be used in CARTA ( such as undo?). Or try to remove unusable options?
![Screenshot 2019-04-22 at 15 19 38](https://user-images.githubusercontent.com/20802551/56488873-5a481180-6512-11e9-816e-d43554ae3158.png)

**Comment by kswang1029** [comment]
I vote for showing only the supported shortcuts to avoid confusions.

**Comment by ajm-asiaa** [comment]
OK. I found a way to hide the Start Dictation and Emoji entries:
```
const {systemPreferences} = require('electron')
systemPreferences.setUserDefault('NSDisabledDictationMenuItem', 'boolean', true)
systemPreferences.setUserDefault('NSDisabledCharacterPaletteMenuItem', 'boolean', true)
```

How is this? 
Only showing Cut, Copy, Paste, and Delete. 
I guess the user may press Delete and use Paste when editing the region properties.
![Screenshot 2019-04-22 at 15 27 47](https://user-images.githubusercontent.com/20802551/56489160-59fc4600-6513-11e9-933f-8f67dd2d3a13.png)

**Comment by kswang1029** [comment]
Nice. 👍 

Do this apply to linux versions too?

**Comment by ajm-asiaa** [comment]
It doesn't work so well for Linux... I thought the Ubuntu menu would be the same as MacOS because the Ubuntu version has a menu bar at the top of the screen with a quit option. But the new Edit menu bar that I add ends up in the CARTA window itself
![Screenshot 2019-04-22 at 15 53 30](https://user-images.githubusercontent.com/20802551/56490235-0c81d800-6517-11e9-860e-a01ae5f4363d.png)

Interestingly for the RedHat7 version running on Ubuntu, there is no Quit option at the top of the screen. This is how it would appear on RedHat7 anyway:
![Screenshot 2019-04-22 at 15 50 04](https://user-images.githubusercontent.com/20802551/56490307-52d73700-6517-11e9-8d6a-1c21a800405d.png)

I will investigate further.

**Comment by ajm-asiaa** [comment]
I think I found a better way to do it using the "electron-context-menu" package. We the copy and paste commands can be hidden behind a right click menu. 
![Screenshot 2019-04-22 at 16 53 17](https://user-images.githubusercontent.com/20802551/56492739-52db3500-651f-11e9-912d-bc54b0b0eb6c.png)

Does CARTA use right click for anything else?

**Comment by veggiesaurus** [comment]
I don't think we'll use right click for anything else in that particular widget. The image view might use right click, and the render config widget already uses right click

**Comment by ajm-asiaa** [comment]
Then that could be a problem because this is just through main.js and enables right click over the entire Electron window, not just on that widget.

**Comment by ajm-asiaa** [comment]
It turns out that it is not a problem at all. Somehow right click in your Render Configuration widget stops the standard right click menu appearing. This is particularly clear when using the server version in a web browser; right click simply sets the max value. Luckily it behaves exactly the same way in Electron with the electron-context-menu package.

I also notice that if we keep the context menu as minimal as possible, it cleverly shows only what options are available at the time. e.g. 'Copy' when only copy is available, or 'Cut', 'Copy', and 'Paste' when those options are available. If there is nothing to cut, copy, or paste, right click does nothing. 

I think I will use this way as the solution.

![Screenshot 2019-04-23 at 08 21 19](https://user-images.githubusercontent.com/20802551/56543056-e6097e80-65a2-11e9-8a71-9893dd6af335.png)
![Screenshot 2019-04-23 at 08 20 48](https://user-images.githubusercontent.com/20802551/56543059-e99d0580-65a2-11e9-82b8-5b46622460b9.png)
![Screenshot 2019-04-23 at 08 22 52](https://user-images.githubusercontent.com/20802551/56543062-ebff5f80-65a2-11e9-87bc-83a2d3905be3.png)

**Comment by ajm-asiaa** [comment]
I encountered some issues..

1. If using only the 'electron-context-menu' on MacOS, keyboard shortcuts to copy and paste ('cmd+c' etc.) do not work. To solve this for MacOS, I propose to use both the context menu, plus a minimal Edit menu on the MacOS menu bar (on the top left of the screen). This would be mostly out of sight.

2. On ubuntu and RedHat7, I don't want to add the Edit menu as it would take up real estate inside the Electron window. I propose to just use the context menu. Plus, luckily on Linux, _most_ of the keyboard shortcut functionality remains;
We can 'ctrl+shift+c' outside the Electron/CARTA window and 'ctrl+shift+v' into CARTA. 
But we can not 'ctrl+shift+v' in CARTA to 'ctrl+shift+c' outside CARTA. 
However, we can just highlight the text in CARTA and use the third mouse button to paste text outside, and vice versa. I guess most people would use that shortcut on Linux desktops? 
(Although I'm not sure if Linux laptops have 3rd button functionality)?
In addition, the right click context menu would allow text to be copied and pasted in CARTA.

**Comment by ajm-asiaa** [comment]
Issue No.2 is solved now. It was very easy in the end. I have just noticed that if we add the Edit menu, then hide menus in the next line, we still get the proper keyboard shortcut functionality and the Edit menu does not appear!
```
require('./menu/mainmenu');
mainWindow.setMenuBarVisibility(false);
```
Interestingly, the proper edit menu allows the copy command to be ctrl+c, not shift+ctrl+c etc.

**Comment by ajm-asiaa** [comment]
I feel this is sorted out now. I tried it on MacOS, RedHat7, and ubuntu. It seems to work.
https://github.com/CARTAvis/carta-package/commit/5c0843818a5b8b9933641ee1c89c5c12133dd621#diff-7a9076d6d94e62c13d641aa71f19ae8e

@kswang1029 will be able to test it tomorrow when I make a new MacOS package.
