### ISSUE TITLE
Increase frequency of spectral profile updates if HDF5 file has a ZYXW dataset available

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-frontend#248]
Part of #45. Described in https://docs.google.com/document/d/1T1T85zvGHy7IsePwztN7SjrMPJ4hQJv8X5ihZKf5XA8/edit#heading=h.2fonicmwctib

**Comment by veggiesaurus** [comment]
one issue with this is that we currently have no way for the frontend to know whether the HDF5 file in question has a rotated dataset. In order to do this, we need additional fields in the ICD to describe the file's feature set properly. 

@arusstaylor I think this means it will have to wait until after 1.1. There are some files in ILIFU which are missing the rotated dataset, @confluence might have to double-check the default settings for her converter.

**Comment by arusstaylor** [comment]
> On Apr 15, 2019, at 10:03 AM, Angus Comrie <notifications@github.com> wrote:
> 
> one issue with this is that we currently have no way for the frontend to know whether the HDF5 file in question has a rotated dataset. In order to do this, we need additional fields in the ICD to describe the file's feature set properly.
> 
> @arusstaylor <https://github.com/arusstaylor> I think this means it will have to wait until after 1.1. There are some files in ILIFU which are missing the rotated dataset, @confluence <https://github.com/confluence> might have to double-check the default settings for her converter.
> 
> 
Yes indeed, the default behaviour should be to create the rotated data set.  Is there a way to tell which ones do not have it? We could remove those files or recreate.

Russ

**Comment by veggiesaurus** [comment]
We can go through them manually and check their header using `h5dump -h`. The issue with automatically enabling this for HDF5 files is that HDF5 files without a rotated dataset would really struggle with realtime profiles.
