### ISSUE TITLE
mis-aligned range index with current index in the animator

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#399]
this issue is more prominent with cubes with just few channels as the following example.

<img width="575" alt="Screen Shot 2019-07-23 at 14 16 08" src="https://user-images.githubusercontent.com/20819712/61687309-b100f980-ad54-11e9-8ee6-6b762c56f095.png">
<img width="1046" alt="Screen Shot 2019-07-23 at 14 18 48" src="https://user-images.githubusercontent.com/20819712/61687364-d4c43f80-ad54-11e9-9806-ab78c991d89f.png">

**Comment by veggiesaurus** [comment]
the root cause of this issue is that the BlueprintJS slider widget expects equally spaced tick labels, so it's dividing the range into 4 sections (5 labels). Since this often doesn't result in an integer, the tick labels are actually offset from the slider itself by up to one channel. I'm not sure how to solve this, because if we force the tick spacing to be an integer, then we can't ensure that there will be a tick at the last channel. 

e.g. perfectly lined up labels. but missing tick at the end:
![image](https://user-images.githubusercontent.com/592504/61694232-5efaac80-ad31-11e9-800b-2800e2262932.png)

**Comment by kswang1029** [comment]
The probability for a user to view a cube with just few channels should be low (but not negligible). From this point of view, this issue should be less noticeable. Let's set it low priority?

**Comment by kswang1029** [comment]
On hold since labels of the sliders in the animator will need to be revised significantly for v1.3. Will double check again this issue once sliders are revised.

**Comment by kswang1029** [comment]
fixed by https://github.com/CARTAvis/carta-frontend/pull/1891
