### ISSUE TITLE
[user request] breadcrumbs in filebrowser

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#400]
> Hello,
> 
> I am an active user of CARTA. While browsing through the directory structure I regularly get lost because I have no indication in what path I am (see attachment). Therefore I suggest to implement breadcrumbs [0] which would help with orientation.
> Thanks a lot and I really like the software!
> 
> [0] https://blueprintjs.com/docs/?origin_team=T3630BF32#core/components/breadcrumbs
> 
> Kind regards,
> Lennart

<img width="431" alt="Screen Shot 2019-07-23 at 14 36 56" src="https://user-images.githubusercontent.com/20819712/61688340-5e750c80-ad57-11e9-9791-263eb814e87d.png">
<img width="429" alt="Screen Shot 2019-07-23 at 14 36 44" src="https://user-images.githubusercontent.com/20819712/61688341-5e750c80-ad57-11e9-8d93-f2f3bd262108.png">

**Comment by veggiesaurus** [comment]
Since 1.2 is a "usability"-focused release (with performance falling under usability), I decided to quickly implement something as a starting point. There's a little bit of a clash in terms of styling, but I do feel like we should improve the file list's styling in future, to make it fit in with the rest of the interface. 

![breadcrumbs](https://user-images.githubusercontent.com/592504/61795880-a877f400-ae24-11e9-81ee-97ef39b28580.gif)

**Comment by kswang1029** [comment]
@veggiesaurus this is nice! what happens with an exclusively long path?

**Comment by veggiesaurus** [comment]
exclusively long path?

**Comment by kswang1029** [comment]
like 10-level folder structure

**Comment by veggiesaurus** [comment]
It looks like this:

![image](https://user-images.githubusercontent.com/592504/61797233-410f7380-ae27-11e9-8441-c9daf646b00c.png)

![image](https://user-images.githubusercontent.com/592504/61797330-7b791080-ae27-11e9-8129-7a31c3ff40fc.png)

**Comment by kswang1029** [comment]
Just realized I can try it. This is an example with standard ALMA data folder structure. 
![Jul-24-2019 21-28-07](https://user-images.githubusercontent.com/20819712/61797437-fce99680-ae59-11e9-99ce-cd3f6d6c3a04.gif)
