### ISSUE TITLE
Zooming in a profile in point style results in empty plot

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#453]
The following is an example with 7860 channels. With much fewer channels (e.g 100), it is harder to trigger this issue.
![Aug-07-2019 10-34-23](https://user-images.githubusercontent.com/20819712/62590914-7a081780-b900-11e9-987b-295df906cf32.gif)

**Comment by veggiesaurus** [comment]
@panchyo0 can you see if this is still an issue with the latest version of chartjs?

**Comment by panchyo0** [comment]
with 2.9.3 the bug still there. 3.0.0-alpha will cause crush from start. This bug only happened, if I zoom in really really fast or I continue zoom in to the end. To fix it we can check `currentRange = this.props.xMax - this.props.xMin`, if currentRange < SomeReallySmallNumber, then we stop zoom. Not sure what should be the `SomeReallySmallNumber`. zoom will trigger the empty table when  `currentRange` smaller than 10e-12. Is  10e-11 sufficient for all case?

**Comment by veggiesaurus** [comment]
What if we limit it to the gap between two points?

**Comment by panchyo0** [comment]
Did you mean, we calculate the distance for each points pair ({point 1, point 2}, {point2, point3} ...) and find the min distance form there?

**Comment by veggiesaurus** [comment]
Something like that might work. Or we can just take an estimate, perhaps?

**Comment by panchyo0** [comment]
http://carta.asiaa.sinica.edu.tw/frontend/8a03835/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev
@veggiesaurus I check the current points (number of visible points < 1) in the view to stop zoom rather than check the gap. since we just pass the array length, this doesn't need any calculation. However this only fix the bug when user continue zoom into the end. `really fast` zoom still cause empty table. Can we use a small `zoomSpeed` in `onStageWheel`?
