### ISSUE TITLE
Region name not used in imported region

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-frontend#523]
Sent from backend in IMPORT_REGION_ACK regions[ ] regionInfo regionName (when set in region file).

**Comment by zarda** [comment]
The ImportRegionAck.region[ ].regionInfo.regionName is empty.

**Comment by zarda** [comment]
There is no any information about region name in the CRTF file. I guess this is the reason where no region name is. @pford 
Another issue is about updating region name. After we rename a region, the frontend need to update the region name in the backend by sending a SET_REGION. Or there is no updated region name in the EXPORT_REGION message, then the backend could unable to store new name into file. @veggiesaurus

**Comment by veggiesaurus** [comment]
We initially put the name parameter into `SET_REGION`, but I don't think we're sending it from the frontend, because I wanted to make sure that updating the region name doesn't trigger any region-related analysis. The backend would have to check if all of the region parameters other than name are the same. @pford does it already do this? I also don't want to spam the backend with `SET_REGION` updates while the user is updating the region name, but this is a little easier to work around. 

The alternative would be to send the region names only in `EXPORT_REGION` message. Perhaps we could switch from using `region_id: int32[]` to `region_names: map<int32, string>` (where the key is the `region_id` and the value is the region name`.

**Comment by zarda** [comment]
Tested a .crtf file with label='xxx' and the region name will show up well. I will push the branch.

**Comment by zarda** [comment]
Region name/label exporting will be another issue. May we close this issue?
