### ISSUE TITLE
capitalize Ascension in axis label

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#548]
Right ascension should be Right Ascension.

This should be fixed urgently and included in patch.  Need to produce publication images suitable for publication.  See image in next comment.

**Comment by arusstaylor** [comment]
![mosaic_geometry](https://user-images.githubusercontent.com/9055533/66254919-66045900-e77d-11e9-88f5-a472b2276d55.png)

**Comment by arusstaylor** [comment]
also the background should be white by default not blue-grey.  Or it should be settable in the overlay settings.

**Comment by arusstaylor** [comment]
I need this corrected for a publication.   Can the fix  go into a dev version at IDIA?

**Comment by veggiesaurus** [comment]
@arusstaylor I really don't think this falls into the category of "critical bug", as it does not cause an irrecoverable crash.

We use the AST library for producing  the coordinate grid overlay and labels, and as such, we are consistent with all other software packages using the AST library. This includes the text content of the labels themselves. I'd rather not break this consistency for the sake of capitalisation (I've just checked, and DS9 produces "Right ascension" as well). What we could do, however, is re-introduce the ability to edit title and label text manually. Would that solve this issue?

As for the background, I agree it should not be blue-grey. I'd argue that the background should be transparent, so that exported images can be used with any background colour down the line. This should be reasonably easy to fix.

**Comment by arusstaylor** [comment]
OK. Not aware of the meaning of critical bug.  My intention was to note that this problem makes the feature unusable for its intended purpose, which is to create pictures for publication.  Cannot publish with this error.    Looks like an error in the AST library.  Ability to edit title and label text manually and to set the background colour (including a transparent option) would fix this.

**Comment by veggiesaurus** [comment]
The AST repo is here: https://github.com/Starlink/ast/issues, perhaps you could file an issue there? Using title case, rather than sentence case for a label seems like a preference, rather than a bug. Possibly there is already an option for this in AST though (the documentation is quite extensive)

**Comment by arusstaylor** [comment]
The issue is journal style for publications.  Having the option to edit the title to change the capitalisation to tile case solves the problem.

**Comment by veggiesaurus** [comment]
I've created two separate issues (#550 and #549), so I'll close this issue for now and we can keep track of the two issues separately.
