### ISSUE TITLE
Catalog overlay: design doc

### ISSUE THREAD

**Issue by panchyo0** [CARTAvis/carta-frontend#571]
- [x] Sequence diagram (How frontend request catalog data from the backend) [doc](https://docs.google.com/document/d/1mD9cZri8S25hm6VTPehEXUXA_kDptlcr41ktbEZQv1k/edit#heading=h.get8b5g447o)

- [x] Message Formats [doc](https://docs.google.com/document/d/1mD9cZri8S25hm6VTPehEXUXA_kDptlcr41ktbEZQv1k/edit#heading=h.get8b5g447o)

- [x] Mock-up [doc](https://docs.google.com/document/d/1mD9cZri8S25hm6VTPehEXUXA_kDptlcr41ktbEZQv1k/edit#heading=h.get8b5g447o)

**Comment by veggiesaurus** [comment]
@panchyo0 the first step is to define how we will request the data from the backend, how the backend will deliver the data. Once that is defined, one of the backend developers can start working on delivering the data to the frontend using the method you've designed. See the ICD for details on this

**Comment by arusstaylor** [comment]
what if the data catalogue is on the client?  Could we import from the front end?

**Comment by veggiesaurus** [comment]
> what if the data catalogue is on the client? Could we import from the front end?

In future, we could write a browser-based VOTable parser for loading client-side data, because they're XML-based, and should be reasonably easy to adapt. For other formats, it will be more difficult. The other option is to send the catalogue to the backend first before its parsed and streamed _back_ to the frontend, but that seems like a roundabout route. 

For the 1.3 release, I suggest we stick to backend data (like we currently do for region files as well)

**Comment by panchyo0** [comment]
finished. doc at https://docs.google.com/document/d/1mD9cZri8S25hm6VTPehEXUXA_kDptlcr41ktbEZQv1k/edit#heading=h.x2klaba3o6j1
