### ISSUE TITLE
Incorrect velocity calculated from frequency headers

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-frontend#653]
The velocity computed from the FileInfoExtended frequency headers is incorrect (backend issue 377).  Logging the input freq and refFreq input values to velocityFromFrequency in utilities/units.ts to the console, it looks like the frontend is using rounded values from the HeaderEntry string value rather than the numeric value.  The velocity changed when the string formatting of RESTFRQ and CRVALn headers for FREQ axis was changed but the numeric values remained the same.

This issue needs to be fixed for the 1.2 patch release.

**Comment by veggiesaurus** [comment]
this should be reasonably easy to fix, but I think this is going to be more of a general problem, because the frontend uses the WCS headers (in string form) as arguments for the AST library for coordinate transformations, and this will soon be extended to spectral value conversions (#647 , #648). @pford shouldn't the headers be sent exactly as they are read from the file?

**Comment by pford** [comment]
I assumed the numeric value was used for calculations and the string was user facing.  I think you should leave the frontend as it is (cancel the PR), and I will modify the headers.

**Comment by pford** [comment]
So what are the numeric values for?

**Comment by veggiesaurus** [comment]
If the entries are numeric initially (is this the case for casa and/or miriad?) then we could just use the numeric values, it's probably safer. I think the main thing is that the headers should appear as they are in the file

**Comment by veggiesaurus** [comment]
is this fixed? @pford
