### ISSUE TITLE
No limitation to zoom out until all objects disappear

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-frontend#66]
This issue will happen whenever keeping zooming out. In the render area, user can keep zooming out unlimitedly. This action will cause that all objects on the canvas are gone, and system crash in some case. Another the functionality of zoom in also has no limitation.

**Comment by veggiesaurus** [comment]
@kswang this issue should be combined with #64. Two issues to deal with: 
1) Crash handling when the frame is out of bounds (this is a backend crash, not frontend)
2) We have a limitation in place which prevents panning so that the centre of the FoV is outside of the image. This was put in place to prevent users from getting lost. There are a few issues with this approach:
a) The problem is that the scroll-zooming approach keeps the pixel under the cursor fixed while zooming, which can lead to situations where the center of the FoV is outside the image, and due to the constraints, there's no way to get back (see below)
b) When we move to overlaying raster images and contour images, this is an arbitrary constraint. 

How do we proceed? Obviously the backend needs to fix the crash, as a starting point. As for the frontent, my initial suggestion would be to remove the constraint on panning to fix (a), and to add a "fit to screen" zoom button to the quick settings overlay that will (eventually) be added to the image viewer, which will allow the user to return to the default view. I agree that we should limit the max/min zoom ranges. The AST overlay breaks down as soon as we set the field of view greater than the maximum physical range (see below). So what do we limit it to, bearing in mind that we eventually want to be able to zoom out to view all images in a WCS group. For simplicity, we could try limit it to the maximum physical range (full-sky)

![zoom_fov](https://user-images.githubusercontent.com/592504/47346806-32d0d300-d6ae-11e8-97b4-fa97944f9c90.gif)

![image](https://user-images.githubusercontent.com/592504/47347338-51839980-d6af-11e8-8cbc-5ede4d0be240.png)

**Comment by veggiesaurus** [comment]
I've checked DS9, and the weird rendering behaviour also occurs with it, so it's definitely an AST issue.

**Comment by kswang1029** [comment]
For 1, yes, backend should check the frontend message "SET_IMAGE_VIEW" before actually preparing "RASTER_IMAGE_DATA". 

For the zoom limit, some projection types are unbounded (diverge at "edges", actually edges cannot be defined), so maybe it is hard to define a "full sky" zoom level. I was thinking maybe we could use the actually image size on screen as a constraint to stop zooming out. If the image size is less than say 50 screen pixel, we probably can stop zooming out since the only information we can tell is that "oh there is an image there and that's it". The actual content of that small patch I believe no one can really tell and perform any further analysis with it. What do you think about this solution?

The other issue about WCS group is that in some projection types, we can only see up to a hemisphere, not full sky. So if users open two images which are actually located in opposite hemisphere, we may have a problem. The simplest way is throw a warning in this case that we cannot show the images in this scenario. 
May not be totally relevant but this is an interesting work: 
http://ofrohn.github.io/celestial-demo/map.html
and maybe HEALpix lib and viewer could be a solution for this issue.

**Comment by veggiesaurus** [comment]
I like that idea. But it should be the bounding box of all images in the WCS group, right? (rather than the bounding box of a single image). Gets a bit tricky when you remove an image then, as the bounding box will change. I think this needs to happen _after_ the WCS group implementation, although we can temporarily implement the constraint for a single image if it's urgent

**Comment by kswang1029** [comment]
if the two images separate almost 180 degrees, the joint bounding box would be large. Not sure if AST is still stable if we zoom out to the state that the joint box is ~50 screen pixel in size. May be worst to test it.

**Comment by kswang1029** [comment]
Perhaps we can use the image with largest FOV in the WCS group as a constraint to set the scale we start to forbid further zooming out. If that image reaches ~50 screen pixel, we set the scale there. In this case, the other smaller FOV images may be super tiny. But I think AST will still be stable. Again, we need tests.
