### ISSUE TITLE
render config plots have no y axis

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-frontend#690]
might be nice to add y-axis label to the render config plots. Like the number of pixels for a given value.

**Comment by veggiesaurus** [comment]
@kswang1029 and I discussed this, and ended up deciding that the y-axis labels are not needed for the render config and contour config plots, because they take up quite a bit of space (especially on a MBP 13" screen!), and a user can always open a histogram widget for more detailed analysis. Easy to add the y-axis back if consensus is that it should be there.
