### ISSUE TITLE
polarization contours

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#707]
We need the ability to plot polarised intensity contours in the case the contour source file has Stokes planes.  Option should be to plot contours from any of the Stokes planes or, if Q and U are present, to plot P contours, where P is the usual sqrt(Q*Q + U*U).

**Comment by veggiesaurus** [comment]
Would it not make sense to make this more generic, so you could also view P for a Stokes cube as a raster image?

**Comment by arusstaylor** [comment]
yes.  Also, in principle, should be able to plot position angle as a raster or contour.

**Comment by kswang1029** [comment]
I guess we can add options in the file browser as "generate PI" and "generate PA" when a valid Stokes cube is selected. So once this cube is loaded, we see three "frames" (IQU, PI, and PA) in the animator. Then we can follow the current design to generate contour layers on top of any raster images.

**Comment by arusstaylor** [comment]
I dont think this should be an option that the user has to select in the file browser.  That strikes me as clunky user interface.  For a Stokes cube I think PI and PA should just appears as options for overlays in the overlay and contour tools and should also appear as options in the Stokes drop down in the z-profile tool.    (I suppose this latter should be a separate issue).

**Comment by veggiesaurus** [comment]
I agree that it would make more sense to do this on the fly, rather than the user having to generate an entire cube's PI and/or PA when they load the file. What I'm proposing is that we effectively treat PI and PA as additional "Stokes" values everywhere that we have a Stokes dropdown

The issue then becomes how to plot contours from one Stokes channel (I, Q, U, V, PI, PA) on top of another. There are a few solutions to this:
1. Allow users to easily "duplicate" files so that you can open the same image twice with multiple channels/stokes
2. Allow users to enable or disable auto-updating of contours when the image's channel or Stokes changes
3. Allow users to copy generated contours and paste them as a new layer. 
4. Allow users to effectively open multiple Stokes sub-cubes at once in the same image. 

1 and 2 are relatively simple. 3 is something we probably want to do anyway. 4 is _really_ tricky, and will require massive changes to a huge amount of the ICD, and a big rethink of the UI. 1 and 4 will both effectively double memory usage (since you'll have multiple channels in memory at a time), but will allow users to have contours for a specific Stokes overlaid on top of another Stokes, and still have them update as the channel changes. 2 and 3 both don't increase memory usage by much, but would prevent contours from being automatically re-generated when channels change. 

I'm heavily against attempting 4, unless the wider community absolutely demands it. It will be a serious headache. I would suggest that we implement 1, 2 and 3, and give users plenty of options in terms of how they want to handle these situations. 

(edit: to clarify, "duplicating" in this context just means a one-click way of opening the same file again, not duplicating the data on disk or anything)

**Comment by arusstaylor** [comment]
Agree that PI and PA should just appear as additional Stokes values in drop downs.

Is there any reason why the same file cannot be loaded with both "load" and "append"?  Is this what you mean by duplicate?  

I agree we want 2 anyway to allow contours from a different channel or Stokes to be overlaid on a  given channel/Stokes.  Do you really need to load the whole file again to plot contours from a different stokes or channel of the same cube?  Could one not just disable auto-updated and select a fixed Stokes and channel from the input cube for the contours?

We want the ability to save contours to a file, so a user could save contours to a file and then load the contours from the saved file as a new layer.

Not sure what is meant by 4.  But sounds confusing.

**Comment by veggiesaurus** [comment]
> Is there any reason why the same file cannot be loaded with both "load" and "append"? Is this what you mean by duplicate?

Exactly. I'm thinking of the "duplicate" button as a shortcut for appending the same file again. 

> I agree we want 2 anyway to allow contours from a different channel or Stokes to be overlaid on a given channel/Stokes. Do you really need to load the whole file again to plot contours from a different stokes or channel of the same cube? Could one not just disable auto-updated and select a fixed Stokes and channel from the input cube for the contours?

If you want to plot Stokes Q contours on Stokes I raster, but you _also_ want the contours to update automatically as you change channel, then 2 would not suffice, which is why I'd suggest supporting both methods (since they are both quite simple to implement) to give the user some flexibility. For smaller images, the extra memory usage won't be so much of an issue.

> 
> We want the ability to save contours to a file, so a user could save contours to a file and then load the contours from the saved file as a new layer.

Yes, this (and copy/paste) would be similar to how DS9 handles it.

> Not sure what is meant by 4. But sounds confusing.

Exactly... I'm not sure either, but it has been suggested before (although poorly defined). I think we're on the same page though 👍 

My suggestion is that we split this discussion thread into a few issues: 
1. Extending Stokes dropdowns to support PI and PA (not sure this will make it to 1.3, it will require quite a bit of backend work to do this efficiently without doubling the memory usage, and would have to support _all_ analytics as well)
2. UI for enabling/disabling auto-updating of contours
3. "Duplicate" button (we clearly need a better term for this though. Perhaps "duplicate layer" is less confusing)
4. Copy/paste of contours
5. Load/save of contours in DS9 format

**Comment by veggiesaurus** [comment]
Closing this, as the issues have now been separated into #714, #715, #716
