### ISSUE TITLE
reported axes dimensions for regions

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#862]
Looks like the axes dimensions in the region edit widget is reporting semi-major axes but listed as maj: and min:  Should change the values to major and minor axes. 

<img width="1624" alt="Screenshot 2020-04-06 at 09 43 02" src="https://user-images.githubusercontent.com/9055533/78583127-3ea14e00-77eb-11ea-9232-bf57505339bc.png">

**Comment by kswang1029** [comment]
confirmed, and this is nothing to do with HiDPi.

**Comment by kswang1029** [comment]
@arusstaylor @veggiesaurus @pford @duidae 
There is a consistency issue here: when we export a region to casa format or ds9 format with casaViewer and CARTA (they use the same code I guess), the exported ellipse is in semi-major and semi-minor axes. So currently the frontend and the backend are consistent, except we should show as "semi-maj" and "semi-min" instead of "maj" and "min" in the frontend. 

Do you prefer we "display" as major/minor and "export" as semi-major/semi-minor? Or we display _and_ export as semi-major/semi-minor? For compatibility (casaviewer or early versions of CARTA) we better still use semi-axis when export. 

UPDATE:
both ds9 and casa define an ellipse with "radius". ie semi-major and semi-minor axes

**Comment by veggiesaurus** [comment]
> both ds9 and casa define an ellipse with "radius". ie semi-major and semi-minor axes

right, we should be consistent with those approaches, and consistent with the formats that we export to. What if we just use `X: <...>; Y: <...>`? `Semi-maj` and `Semi-min` take up quite a bit of space, and would require us to increase the size column of the region list
