### ISSUE TITLE
frozen when trying to sort a very long file list in the file browser 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#968]
When there are thousands of image files in a folder, sorting (name, type, or size) is extremely slow and could case UI frozen.

**Comment by veggiesaurus** [comment]
This is almost exclusively due to the HTML table we've been using. We should definitely move to a virtual table approach, either using blueprintJS or another react-based package. 

For me, showing 10000 FITS files in the file browser used over 800 MB of memory in Chrome, which is definitely a problem

**Comment by veggiesaurus** [comment]
Just cobbled something together using Blueprint table. Still needs plenty of feature work and styling, but it certainly fixes the issue. This is with 10 000 FITS files on an SSD:
![file_browser_table](https://user-images.githubusercontent.com/592504/86287101-e5796880-bbe7-11ea-88e3-96c707d66b8d.gif)

**Comment by veggiesaurus** [comment]
> For me, showing 10000 FITS files in the file browser used over 800 MB of memory in Chrome, which is definitely a problem

Now using barely any extra memory when displaying lots of files in PR #976
