### ISSUE TITLE
[overlay settings] labels and numbers

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#98]
Now with "Toggle labels"  button on the image viewer when hovering on, the GUI state is not sync'd. When "Toggle labels" is False, the two "visible" are still True in the overlay settings.
<img width="1431" alt="screen shot 2018-12-07 at 13 12 46" src="https://user-images.githubusercontent.com/20819712/49629027-624f5b00-fa22-11e8-8804-27dde05dea75.png">

I suggest we rename "Toggle labels" to "Toggle labels and tick numbers" or something similar to be consistent with what it actually does. We will need to make sure the UI state is sync'd. 

Do we really need "Toggle labels"  button? Not sure this is a commonly used action to turn off labels and tick numbers. We can keep it for now and listen to what users think.

**Comment by veggiesaurus** [comment]
do you think it's sufficient to just allow the user to toggle labels and numbers together, rather than independently?

**Comment by veggiesaurus** [comment]
alternatively: clicking the toggle button on the quick access toolbar (probably how most users will adjust these settings) toggles them both on/off, while the menu can be used for custom settings

**Comment by kswang1029** [comment]
Good idea. I don't think displaying just one of them is useful. Binding them together is better.

**Comment by kswang1029** [comment]
I like the alternative solution too.

**Comment by veggiesaurus** [comment]
@confluence can you implement this fix today?

**Comment by confluence** [comment]
The intention here is to temporarily override whatever the individual settings are in order to hide all currently set labels. This is not intended to change the settings, hence the "hide" terminology. I would prefer not to have this button permanently set or unset these settings -- that would mean that using the button for convenience permanently obliterates the user's custom selection of elements to show and hide. I see this feature as analogous to the preview mode in a drawing program which hides box borders, guides and other layout elements.

We do currently set and unset the grid visibility directly, because it's just one setting corresponding to one button, but I'm not 100% sure if it wouldn't be better to add a separate setting to override the visibility. But this will probably only be important once we start saving and restoring custom user settings (because the user might want the grid to be off by default, but we may want the toggle grid button to be on by default).

I'd be happy to change the tooltip text for clarity, but the setting *also* affects the title (but you may not have seen that because it's off by default anyway). If we explicitly mention all three things, that's going to be a long tooltip. "Labels" is intended to be a generic term encompassing the text labels, numeric labels and title.

**Comment by veggiesaurus** [comment]
That's a good point. And adding three separate icons would be rather annoying. @kswang1029 thoughts? In my mind, the purpose of the toggle is to switch between a mode where the user has all the information they want visible, and a mode where all the real estate is used for the image itself.

**Comment by veggiesaurus** [comment]
I think it's good to keep the border and ticks. They don't obscure the view of the image much, and they help a lot when working out where things are

**Comment by kswang1029** [comment]
Thank you @confluence @veggiesaurus After thinking a while, maybe we can have a toggle to enable the entire overlay settings so that users can fine tune the appearance of the image plot. Would that be easier without sacrificing too much UX?

**Comment by confluence** [comment]
@kswang1029 could you please elaborate on what you mean by "toggle to enable the entire overlay settings"? Do you mean adding a lot more buttons to toggle specific elements?
