### ISSUE TITLE
broken layout issues associated with catalog widget and scatter plot widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#980]
To reproduce:
1) load an image and a catalog and enable 2D scatter plot
2) dock the 2D scatter plot and save the layout (eg cat_scatter1)
3) undock the 2D scatter plot (as a floating widget) and save the layout (eg cat_scatter2)
4) reload CARTA

Now there are two issues:
5) once CARTA is just reloaded, switch to cat_scatter1 and we will see the catalog widget is disappeared (scatter plot widget too)
6) once CARTA is just reloaded, switch to cat_scatter2 and we will see the frontend crashes with a blank page.

**Comment by veggiesaurus** [comment]
@duidae will you work with @panchyo0 to expand the layout support to include catalogs? @panchyo0 it would also be great if we could include the (percentage) position of the vertical divider in the layout

**Comment by duidae** [comment]
ok

**Comment by duidae** [comment]
@veggiesaurus @panchyo0 @kswang1029 , about supporting saving scatter plot widget in layout, there may be some issues needed to be considered:

1. Once I dock both catalog overlay widget & scatter plot widget and save this layout, seems something breaks when restart frontend.
2. Scenario of saving ONLY scatter plot widget: do we need to support this? because so far it is not feasible since closing catalog overlay widget will also close scatter plot widget.

**Comment by duidae** [comment]
@panchyo0 @veggiesaurus I've added the layout support for catalog/scatter plot in **jason/layout_support_catalog** branch, and since catalog widget has a special design for the widget id & scatter plot, the rest may need your help for the id part & deciding whether to support scatter plot or not in layout.

**Comment by veggiesaurus** [comment]
we should add a separate issue for improving the catalog support in layouts after adjustments to the catalog UI are made
